### ISSUE TITLE
git download | zip download missing files in nova-pinball-engine

### ISSUE THREAD

**Issue by ds2k5** [wesleywerner/nova-pinball-engine#3]
Hi,
if i download with git ( https://github.com/wesleywerner/nova-pinball ) or the zip file
the directory: nova-pinball-engine is empty

thanks

**Comment by wesleywerner** [comment]
@ds2k5 the nova-pinball-engine directory is actually a git submodule that links to another repository. To initialize and pull submodules in git:

You must run two commands: `git submodule init` to initialize your local configuration file, and `git submodule update` to fetch all the data from that project and check out the appropriate commit listed in your superproject.

https://git-scm.com/book/en/v2/Git-Tools-Submodules

Thanks 😃

**Comment by ds2k5** [comment]
Thanks Werner,

now it works.

git clone https://github.com/wesleywerner/nova-pinball
cd nova-pinball
git submodule init
submodule update
cd ..

love nova-pinball
